# Generated by Django 6.0.8 on 2026-08-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsec_rules', '0001_rule_evaluation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruleevaluation',
            name='framework',
            field=models.CharField(choices=[('MASVS', 'OWASP MASVS'), ('ATTACK_MOBILE', 'MITRE ATT&CK Mobile'), ('DYNAMIC_RUNTIME', 'MSAP Dynamic Runtime')], max_length=32),
        ),
    ]
