apiVersion: v1
kind: Service
metadata:
  name: {{ include "msap.componentName" (dict "root" . "component" "frontend") }}
  labels:
    {{- include "msap.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    {{- include "msap.selectorLabels" (dict "root" . "component" "frontend") | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
