{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "msap.fullname" . }}
  labels:
    {{- include "msap.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- with .Values.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "msap.componentName" (dict "root" $ "component" "backend") }}
                port:
                  name: http
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "msap.componentName" (dict "root" $ "component" "frontend") }}
                port:
                  name: http
    {{- end }}
{{- end }}
