{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "msap.componentName" (dict "root" . "component" "redis") }}
  labels:
    {{- include "msap.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  selector:
    {{- include "msap.selectorLabels" (dict "root" . "component" "redis") | nindent 4 }}
  ports:
    - name: redis
      port: {{ .Values.redis.port }}
      targetPort: redis
{{- end }}
