{{- if .Values.backend.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "msap.backendServiceAccountName" . }}
  labels:
    {{- include "msap.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
automountServiceAccountToken: false
---
{{- end }}
{{- if .Values.worker.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "msap.workerServiceAccountName" . }}
  labels:
    {{- include "msap.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
automountServiceAccountToken: false
---
{{- end }}
{{- if .Values.frontend.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "msap.frontendServiceAccountName" . }}
  labels:
    {{- include "msap.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
automountServiceAccountToken: false
{{- end }}
