# Generated by Django 6.0.8 on 2026-08-08 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apk_files', '0001_initial'),
        ('audits', '0003_analysisjob_result_summary'),
        ('evidence', '0001_initial'),
        ('findings', '0002_finding_details_and_unique'),
        ('storage', '0003_alter_objectstoragereference_object_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('representation_type', models.CharField(choices=[('JADX_SOURCE', 'JADX decompiled source'), ('JADX_JAVA', 'JADX decompiled Java'), ('JADX_KOTLIN', 'JADX decompiled Kotlin'), ('SMALI', 'Smali representation'), ('DEX_DISASSEMBLY', 'DEX disassembly'), ('DEX_METADATA', 'DEX metadata'), ('MANIFEST_XML', 'Decoded AndroidManifest.xml'), ('RESOURCE_XML', 'Decoded resource XML'), ('NETWORK_SECURITY_XML', 'Decoded network security XML'), ('NATIVE_SYMBOL', 'Native binary/symbol metadata'), ('APK_SIGNING_METADATA', 'APK signing metadata'), ('CERTIFICATE_METADATA', 'Certificate metadata'), ('OTHER_TEXT', 'Other generated text')], max_length=64)),
                ('logical_path', models.CharField(max_length=1024)),
                ('display_path', models.CharField(max_length=1024)),
                ('language', models.CharField(blank=True, max_length=64)),
                ('class_name', models.CharField(blank=True, max_length=512)),
                ('package_name', models.CharField(blank=True, max_length=512)),
                ('sha256', models.CharField(max_length=64)),
                ('line_count', models.PositiveIntegerField(default=0)),
                ('generated_by', models.CharField(max_length=255)),
                ('tool_version', models.CharField(blank=True, max_length=128)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('apk_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_documents', to='apk_files.apkfile')),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_documents', to='audits.audit')),
                ('storage_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_documents', to='storage.objectstoragereference')),
            ],
            options={
                'ordering': ['logical_path', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FindingSourceReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('representation_type', models.CharField(choices=[('JADX_SOURCE', 'JADX decompiled source'), ('JADX_JAVA', 'JADX decompiled Java'), ('JADX_KOTLIN', 'JADX decompiled Kotlin'), ('SMALI', 'Smali representation'), ('DEX_DISASSEMBLY', 'DEX disassembly'), ('DEX_METADATA', 'DEX metadata'), ('MANIFEST_XML', 'Decoded AndroidManifest.xml'), ('RESOURCE_XML', 'Decoded resource XML'), ('NETWORK_SECURITY_XML', 'Decoded network security XML'), ('NATIVE_SYMBOL', 'Native binary/symbol metadata'), ('APK_SIGNING_METADATA', 'APK signing metadata'), ('CERTIFICATE_METADATA', 'Certificate metadata'), ('OTHER_TEXT', 'Other generated text')], max_length=64)),
                ('logical_path', models.CharField(max_length=1024)),
                ('class_name', models.CharField(blank=True, max_length=512)),
                ('method_name', models.CharField(blank=True, max_length=512)),
                ('method_descriptor', models.CharField(blank=True, max_length=1024)),
                ('symbol_name', models.CharField(blank=True, max_length=1024)),
                ('start_line', models.PositiveIntegerField(blank=True, null=True)),
                ('end_line', models.PositiveIntegerField(blank=True, null=True)),
                ('start_offset', models.BigIntegerField(blank=True, null=True)),
                ('end_offset', models.BigIntegerField(blank=True, null=True)),
                ('excerpt', models.TextField(blank=True)),
                ('excerpt_sha256', models.CharField(blank=True, max_length=64)),
                ('locator', models.JSONField(blank=True, default=dict)),
                ('confidence', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=16)),
                ('is_primary', models.BooleanField(default=False)),
                ('provenance', models.TextField()),
                ('source_lines_available', models.BooleanField(default=True)),
                ('unavailable_reason', models.TextField(blank=True)),
                ('reference_fingerprint', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_references', to='findings.finding')),
                ('source_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finding_references', to='evidence.sourcedocument')),
            ],
            options={
                'ordering': ['-is_primary', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='sourcedocument',
            index=models.Index(fields=['audit', 'apk_file'], name='evidence_so_audit_i_6d9c18_idx'),
        ),
        migrations.AddIndex(
            model_name='sourcedocument',
            index=models.Index(fields=['representation_type', 'logical_path'], name='evidence_so_represe_dce2bf_idx'),
        ),
        migrations.AddIndex(
            model_name='sourcedocument',
            index=models.Index(fields=['sha256'], name='evidence_so_sha256_d1b299_idx'),
        ),
        migrations.AddConstraint(
            model_name='sourcedocument',
            constraint=models.UniqueConstraint(fields=('audit', 'apk_file', 'representation_type', 'logical_path'), name='unique_source_document_path'),
        ),
        migrations.AddIndex(
            model_name='findingsourcereference',
            index=models.Index(fields=['finding', 'is_primary'], name='evidence_fi_finding_f47fc3_idx'),
        ),
        migrations.AddIndex(
            model_name='findingsourcereference',
            index=models.Index(fields=['source_document', 'start_line'], name='evidence_fi_source__d09282_idx'),
        ),
        migrations.AddConstraint(
            model_name='findingsourcereference',
            constraint=models.UniqueConstraint(fields=('finding', 'reference_fingerprint'), name='unique_finding_source_fingerprint'),
        ),
    ]
