# Generated by Django 6.0.8 on 2026-08-13 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_analysis', '0009_agentrun_approved_plan_hash_agentrun_assessment_plan_and_more'),
        ('evidence', '0002_sourcedocument_findingsourcereference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='agent_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_records', to='dynamic_analysis.agentrun'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='agent_run_artifact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_records', to='dynamic_analysis.agentrunartifact'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='agent_run_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_records', to='dynamic_analysis.agentrunstep'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='provenance',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='evidence',
            name='sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
