# Generated by Codex on 2026-08-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evidence", "0003_evidence_agent_run_evidence_agent_run_artifact_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evidence",
            name="ai_conclusion",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="evidence",
            name="ai_evidence_strength",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="evidence",
            name="ai_explanation",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="evidence",
            name="ai_explanation_metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="evidence",
            name="ai_explanation_model",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="evidence",
            name="ai_explanation_provider",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="evidence",
            name="ai_explanation_status",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="evidence",
            name="ai_security_impact",
            field=models.TextField(blank=True),
        ),
    ]
