# Generated by Django 6.0.7 on 2026-07-15 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apk_files', '0001_initial'),
        ('audits', '0003_analysisjob_result_summary'),
        ('storage', '0002_objectstoragereference_storage_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawAnalyzerResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analyzer_name', models.CharField(max_length=128)),
                ('analyzer_version', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=32)),
                ('result_summary', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apk_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_analyzer_results', to='apk_files.apkfile')),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_analyzer_results', to='audits.audit')),
                ('storage_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_analyzer_results', to='storage.objectstoragereference')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['audit', 'apk_file'], name='analyzers_r_audit_i_338e35_idx'), models.Index(fields=['analyzer_name', 'status'], name='analyzers_r_analyze_2fb0b8_idx')],
            },
        ),
    ]
