# Generated by Django 6.0.7 on 2026-07-13 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audits', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectStorageReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket', models.CharField(max_length=255)),
                ('object_key', models.CharField(max_length=1024)),
                ('object_type', models.CharField(choices=[('APK_UPLOAD', 'APK upload'), ('EXTRACTED_MANIFEST', 'Extracted manifest'), ('EXTRACTED_RESOURCE', 'Extracted resource'), ('DECOMPILED_CODE_ARCHIVE', 'Decompiled code archive'), ('RAW_ANALYZER_RESULT', 'Raw analyzer result'), ('NORMALIZED_ARTIFACT', 'Normalized artifact'), ('EVIDENCE_SNIPPET', 'Evidence snippet'), ('PDF_REPORT', 'PDF report'), ('JSON_EXPORT', 'JSON export'), ('AI_REDACTED_CONTEXT', 'AI redacted context')], max_length=64)),
                ('content_type', models.CharField(blank=True, max_length=255)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('retention_policy', models.CharField(choices=[('active_audit', 'Active audit'), ('temporary', 'Temporary'), ('archive', 'Archive'), ('export', 'Export')], default='active_audit', max_length=32)),
                ('encryption_status', models.CharField(choices=[('unknown', 'Unknown'), ('expected', 'Expected'), ('verified', 'Verified')], default='unknown', max_length=32)),
                ('redaction_status', models.CharField(choices=[('not_required', 'Not required'), ('pending', 'Pending'), ('redacted', 'Redacted'), ('blocked', 'Blocked')], default='not_required', max_length=32)),
                ('access_scope', models.CharField(choices=[('project', 'Project'), ('audit', 'Audit'), ('worker_internal', 'Worker internal'), ('export', 'Export')], default='audit', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_references', to='audits.audit')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_references', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['bucket', 'object_key'], name='storage_obj_bucket_518f6b_idx'), models.Index(fields=['object_type'], name='storage_obj_object__8b2772_idx'), models.Index(fields=['sha256'], name='storage_obj_sha256_0dcb2d_idx')],
                'constraints': [models.UniqueConstraint(fields=('bucket', 'object_key'), name='unique_object_storage_reference')],
            },
        ),
    ]
