# Generated by Django 6.0.7 on 2026-07-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectstoragereference',
            name='storage_status',
            field=models.CharField(choices=[('PENDING_UPLOAD', 'Pending upload'), ('UPLOADED', 'Uploaded'), ('VERIFIED', 'Verified'), ('FAILED', 'Failed'), ('DELETED', 'Deleted')], default='PENDING_UPLOAD', max_length=32),
        ),
    ]
