# Generated by Django 6.0.8 on 2026-08-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_objectstoragereference_storage_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectstoragereference',
            name='object_type',
            field=models.CharField(choices=[('APK_UPLOAD', 'APK upload'), ('EXTRACTED_MANIFEST', 'Extracted manifest'), ('EXTRACTED_RESOURCE', 'Extracted resource'), ('DECOMPILED_CODE_ARCHIVE', 'Decompiled code archive'), ('RAW_ANALYZER_RESULT', 'Raw analyzer result'), ('NORMALIZED_ARTIFACT', 'Normalized artifact'), ('EVIDENCE_SNIPPET', 'Evidence snippet'), ('PDF_REPORT', 'PDF report'), ('JSON_EXPORT', 'JSON export'), ('AI_REDACTED_CONTEXT', 'AI redacted context'), ('SOURCE_DOCUMENT', 'Indexed source document')], max_length=64),
        ),
    ]
