# Generated by Django 6.0.7 on 2026-07-13 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_id', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=255)),
                ('severity', models.CharField(max_length=32)),
                ('confidence', models.CharField(max_length=32)),
                ('standard', models.CharField(max_length=128)),
                ('category', models.CharField(blank=True, max_length=128)),
                ('recommendation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='audits.audit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
