# Generated by Django 6.0.8 on 2026-08-05 22:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apk_files', '0001_initial'),
        ('audits', '0003_analysisjob_result_summary'),
        ('storage', '0002_objectstoragereference_storage_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('serial', models.CharField(max_length=128, unique=True)),
                ('kind', models.CharField(choices=[('EMULATOR', 'Emulator'), ('PHYSICAL', 'Physical'), ('REMOTE', 'Remote')], max_length=32)),
                ('host_type', models.CharField(choices=[('WINDOWS_WSL', 'Windows WSL'), ('LINUX', 'Linux'), ('MACOS', 'macOS'), ('CI_RUNNER', 'CI runner'), ('OTHER', 'Other')], max_length=32)),
                ('host_identifier', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('LEASED', 'Leased'), ('PREPARING', 'Preparing'), ('BUSY', 'Busy'), ('OFFLINE', 'Offline'), ('UNHEALTHY', 'Unhealthy'), ('QUARANTINED', 'Quarantined'), ('MAINTENANCE', 'Maintenance')], default='MAINTENANCE', max_length=32)),
                ('api_level', models.PositiveIntegerField()),
                ('android_version', models.CharField(blank=True, max_length=64)),
                ('abi', models.CharField(max_length=64)),
                ('avd_name', models.CharField(blank=True, max_length=128)),
                ('is_rooted', models.BooleanField(default=False)),
                ('selinux_mode', models.CharField(blank=True, max_length=64)),
                ('has_frida', models.BooleanField(default=False)),
                ('has_mitm_ready', models.BooleanField(default=False)),
                ('current_snapshot', models.CharField(blank=True, max_length=128)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_health_check_at', models.DateTimeField(blank=True, null=True)),
                ('quarantine_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DynamicAnalysisJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('DYNAMIC_ONLY', 'Dynamic only'), ('COMBINED', 'Combined')], default='COMBINED', max_length=32)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='QUEUED', max_length=32)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('requested_tool_profile', models.CharField(choices=[('ADB_ONLY', 'ADB only'), ('NETWORK_CAPTURE', 'Network capture'), ('FRIDA_BASIC', 'Frida basic'), ('FRIDA_EXTENDED', 'Frida extended'), ('FULL', 'Full')], default='ADB_ONLY', max_length=32)),
                ('requested_interaction_mode', models.CharField(choices=[('PASSIVE', 'Passive'), ('BASIC_AUTOMATION', 'Basic automation'), ('SCRIPTED_SCENARIO', 'Scripted scenario'), ('AUTHORIZED_LOGIN_SCENARIO', 'Authorized login scenario')], default='PASSIVE', max_length=64)),
                ('timeout_seconds', models.PositiveIntegerField(default=1800)),
                ('max_retries', models.PositiveIntegerField(default=0)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('queued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('failure_category', models.CharField(blank=True, choices=[('DEVICE_UNAVAILABLE', 'Device unavailable'), ('SNAPSHOT_RESTORE_FAILED', 'Snapshot restore failed'), ('APK_INSTALL_FAILED', 'APK install failed'), ('APP_LAUNCH_FAILED', 'App launch failed'), ('PROXY_FAILED', 'Proxy failed'), ('TLS_INTERCEPTION_FAILED', 'TLS interception failed'), ('FRIDA_START_FAILED', 'Frida start failed'), ('FRIDA_SCRIPT_FAILED', 'Frida script failed'), ('UI_AUTOMATION_FAILED', 'UI automation failed'), ('EVIDENCE_COLLECTION_FAILED', 'Evidence collection failed'), ('RULE_EVALUATION_FAILED', 'Rule evaluation failed'), ('CLEANUP_FAILED', 'Cleanup failed'), ('TIMEOUT', 'Timeout'), ('OPERATOR_CANCELLED', 'Operator cancelled'), ('UNKNOWN', 'Unknown')], max_length=64)),
                ('failure_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dynamic_jobs', to='apk_files.apkfile')),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_jobs', to='audits.audit')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_dynamic_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DynamicDeviceLease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lease_status', models.CharField(choices=[('REQUESTED', 'Requested'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('RELEASED', 'Released'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='REQUESTED', max_length=32)),
                ('lease_token', models.CharField(max_length=128, unique=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('release_reason', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_device_leases', to='audits.audit')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leases', to='dynamic_analysis.dynamicdevice')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_leases', to='dynamic_analysis.dynamicanalysisjob')),
                ('leased_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dynamic_device_leases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DynamicDeviceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('HEALTH_CHECK', 'Health check'), ('STATUS_CHANGE', 'Status change'), ('LEASE_CREATED', 'Lease created'), ('LEASE_RELEASED', 'Lease released'), ('LEASE_EXPIRED', 'Lease expired'), ('SNAPSHOT_RESTORED', 'Snapshot restored'), ('QUARANTINED', 'Quarantined'), ('CLEANUP', 'Cleanup'), ('ERROR', 'Error'), ('OPERATOR_NOTE', 'Operator note')], max_length=32)),
                ('severity', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='INFO', max_length=16)),
                ('message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dynamic_device_events', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='dynamic_analysis.dynamicdevice')),
                ('lease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='dynamic_analysis.dynamicdevicelease')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DynamicDevicePool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('max_concurrent_leases', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active'], name='dynamic_ana_is_acti_477bfa_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('max_concurrent_leases__gte', 1)), name='dynamic_pool_max_leases_gte_1')],
            },
        ),
        migrations.AddField(
            model_name='dynamicdevice',
            name='pool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='dynamic_analysis.dynamicdevicepool'),
        ),
        migrations.AddField(
            model_name='dynamicanalysisjob',
            name='requested_device_pool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dynamic_jobs', to='dynamic_analysis.dynamicdevicepool'),
        ),
        migrations.CreateModel(
            name='DynamicEmulatorSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('snapshot_type', models.CharField(choices=[('CLEAN_BASE', 'Clean base'), ('INSTRUMENTED_BASE', 'Instrumented base'), ('SESSION_TEMP', 'Session temporary'), ('MANUAL', 'Manual')], max_length=32)),
                ('description', models.TextField(blank=True)),
                ('api_level', models.PositiveIntegerField()),
                ('abi', models.CharField(max_length=64)),
                ('contains_frida_binary', models.BooleanField(default=False)),
                ('contains_public_ca', models.BooleanField(default=False)),
                ('contains_target_apk', models.BooleanField(default=False)),
                ('validation_status', models.CharField(choices=[('UNKNOWN', 'Unknown'), ('VALID', 'Valid'), ('INVALID', 'Invalid'), ('STALE', 'Stale')], default='UNKNOWN', max_length=32)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='dynamic_analysis.dynamicdevice')),
            ],
            options={
                'ordering': ['device', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DynamicSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('QUEUED', 'Queued'), ('WAITING_FOR_DEVICE', 'Waiting for device'), ('LEASING_DEVICE', 'Leasing device'), ('RESTORING_BASELINE', 'Restoring baseline'), ('PREPARING_DEVICE', 'Preparing device'), ('INSTALLING_APK', 'Installing APK'), ('STARTING_CAPTURE', 'Starting capture'), ('STARTING_INSTRUMENTATION', 'Starting instrumentation'), ('LAUNCHING_APP', 'Launching app'), ('EXERCISING_APP', 'Exercising app'), ('COLLECTING_EVIDENCE', 'Collecting evidence'), ('EVALUATING', 'Evaluating'), ('REPORTING', 'Reporting'), ('CLEANING_UP', 'Cleaning up'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('QUARANTINED', 'Quarantined')], default='QUEUED', max_length=64)),
                ('state_reason', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('tool_versions', models.JSONField(blank=True, default=dict)),
                ('network_capture_enabled', models.BooleanField(default=False)),
                ('frida_enabled', models.BooleanField(default=False)),
                ('runtime_ca_enabled', models.BooleanField(default=False)),
                ('ui_automation_enabled', models.BooleanField(default=False)),
                ('cleanup_status', models.CharField(choices=[('NOT_STARTED', 'Not started'), ('IN_PROGRESS', 'In progress'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('PARTIAL', 'Partial')], default='NOT_STARTED', max_length=32)),
                ('quarantine_required', models.BooleanField(default=False)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dynamic_sessions', to='apk_files.apkfile')),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_sessions', to='audits.audit')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='dynamic_analysis.dynamicdevice')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='dynamic_analysis.dynamicanalysisjob')),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='dynamic_analysis.dynamicdevicelease')),
                ('snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='dynamic_analysis.dynamicemulatorsnapshot')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DynamicSessionArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_type', models.CharField(choices=[('DEVICE_STATE', 'Device state'), ('DYNAMIC_SESSION', 'Dynamic session'), ('LOGCAT_EVENT', 'Logcat event'), ('PROCESS_EVENT', 'Process event'), ('COMPONENT_EVENT', 'Component event'), ('ACTIVITY_EVENT', 'Activity event'), ('SERVICE_EVENT', 'Service event'), ('BROADCAST_EVENT', 'Broadcast event'), ('RUNTIME_API_CALL', 'Runtime API call'), ('FRIDA_EVENT', 'Frida event'), ('NETWORK_FLOW', 'Network flow'), ('DNS_EVENT', 'DNS event'), ('TLS_EVENT', 'TLS event'), ('FILE_SYSTEM_EVENT', 'File system event'), ('DATABASE_EVENT', 'Database event'), ('SHARED_PREFERENCE_EVENT', 'Shared preference event'), ('CLIPBOARD_EVENT', 'Clipboard event'), ('PERMISSION_EVENT', 'Permission event'), ('WEBVIEW_EVENT', 'WebView event'), ('SCREENSHOT', 'Screenshot'), ('SCREEN_RECORDING', 'Screen recording'), ('CRASH_EVENT', 'Crash event'), ('ANR_EVENT', 'ANR event'), ('BEHAVIOR_TIMELINE', 'Behavior timeline')], max_length=64)),
                ('category', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('normalized', models.JSONField(blank=True, default=dict)),
                ('redaction_state', models.CharField(choices=[('NOT_REQUIRED', 'Not required'), ('REDACTED', 'Redacted'), ('PARTIAL', 'Partial'), ('REDACTION_FAILED', 'Redaction failed'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=32)),
                ('confidence', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CONFIRMED', 'Confirmed')], default='MEDIUM', max_length=32)),
                ('manual_validation_required', models.BooleanField(default=True)),
                ('correlation_keys', models.JSONField(blank=True, default=list)),
                ('sequence_number', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raw_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dynamic_session_artifacts', to='storage.objectstoragereference')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='dynamic_analysis.dynamicsession')),
            ],
            options={
                'ordering': ['session', 'sequence_number'],
            },
        ),
        migrations.CreateModel(
            name='DynamicSessionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('STATE_TRANSITION', 'State transition'), ('INVALID_TRANSITION', 'Invalid transition'), ('SESSION_FAILED', 'Session failed'), ('SESSION_CANCELLED', 'Session cancelled'), ('SESSION_COMPLETED', 'Session completed'), ('CLEANUP', 'Cleanup'), ('HEARTBEAT', 'Heartbeat'), ('ARTIFACT', 'Artifact'), ('ERROR', 'Error'), ('OPERATOR_NOTE', 'Operator note')], max_length=64)),
                ('severity', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='INFO', max_length=16)),
                ('message', models.TextField(blank=True)),
                ('sequence_number', models.PositiveIntegerField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='dynamic_analysis.dynamicsession')),
            ],
            options={
                'ordering': ['session', 'sequence_number'],
            },
        ),
        migrations.CreateModel(
            name='DynamicSessionStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('state', models.CharField(choices=[('QUEUED', 'Queued'), ('WAITING_FOR_DEVICE', 'Waiting for device'), ('LEASING_DEVICE', 'Leasing device'), ('RESTORING_BASELINE', 'Restoring baseline'), ('PREPARING_DEVICE', 'Preparing device'), ('INSTALLING_APK', 'Installing APK'), ('STARTING_CAPTURE', 'Starting capture'), ('STARTING_INSTRUMENTATION', 'Starting instrumentation'), ('LAUNCHING_APP', 'Launching app'), ('EXERCISING_APP', 'Exercising app'), ('COLLECTING_EVIDENCE', 'Collecting evidence'), ('EVALUATING', 'Evaluating'), ('REPORTING', 'Reporting'), ('CLEANING_UP', 'Cleaning up'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('QUARANTINED', 'Quarantined')], max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=32)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('attempt', models.PositiveIntegerField(default=1)),
                ('message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='dynamic_analysis.dynamicsession')),
            ],
            options={
                'ordering': ['session', 'created_at', 'attempt'],
            },
        ),
        migrations.CreateModel(
            name='DynamicDeviceCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capability_type', models.CharField(choices=[('ADB', 'ADB'), ('ROOT', 'Root'), ('FRIDA', 'Frida'), ('MITMPROXY_ROUTE', 'mitmproxy route'), ('RUNTIME_CA', 'Runtime CA'), ('SNAPSHOT', 'Snapshot'), ('UI_AUTOMATION', 'UI automation'), ('STORAGE_ACCESS', 'Storage access'), ('NETWORK_CAPTURE', 'Network capture')], max_length=32)),
                ('name', models.CharField(max_length=128)),
                ('version', models.CharField(blank=True, max_length=128)),
                ('is_available', models.BooleanField(default=False)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capabilities', to='dynamic_analysis.dynamicdevice')),
            ],
            options={
                'ordering': ['device', 'capability_type', 'name'],
                'indexes': [models.Index(fields=['capability_type', 'name', 'is_available'], name='dynamic_ana_capabil_3fd5dd_idx'), models.Index(fields=['device', 'is_available'], name='dynamic_ana_device__02dee5_idx')],
                'constraints': [models.UniqueConstraint(fields=('device', 'capability_type', 'name'), name='unique_dynamic_device_capability')],
            },
        ),
        migrations.AddIndex(
            model_name='dynamicdevicelease',
            index=models.Index(fields=['lease_status', 'expires_at'], name='dynamic_ana_lease_s_a59a73_idx'),
        ),
        migrations.AddIndex(
            model_name='dynamicdevicelease',
            index=models.Index(fields=['audit', 'job'], name='dynamic_ana_audit_i_bc9515_idx'),
        ),
        migrations.AddIndex(
            model_name='dynamicdevicelease',
            index=models.Index(fields=['device', 'lease_status'], name='dynamic_ana_device__198342_idx'),
        ),
        migrations.AddIndex(
            model_name='dynamicdevicelease',
            index=models.Index(fields=['heartbeat_at'], name='dynamic_ana_heartbe_666bbd_idx'),
        ),
        migrations.AddConstraint(
            model_name='dynamicdevicelease',
            constraint=models.UniqueConstraint(condition=models.Q(('lease_status', 'ACTIVE')), fields=('device',), name='unique_active_dynamic_lease_per_device'),
        ),
        migrations.AddConstraint(
            model_name='dynamicdevicelease',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('lease_status', 'ACTIVE'), _negated=True), ('expires_at__isnull', False), _connector='OR'), name='dynamic_active_lease_requires_expiry'),
        ),
        migrations.AddConstraint(
            model_name='dynamicdevicelease',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('lease_status', 'RELEASED'), _negated=True), ('released_at__isnull', False), _connector='OR'), name='dynamic_released_lease_requires_time'),
        ),
        migrations.AddIndex(
            model_name='dynamicdeviceevent',
            index=models.Index(fields=['device', 'created_at'], name='dynamic_ana_device__82d023_idx'),
        ),
        migrations.AddIndex(
            model_name='dynamicdeviceevent',
            index=models.Index(fields=['event_type', 'severity'], name='dynamic_ana_event_t_d3141e_idx'),
        ),
        migrations.AddIndex(
            model_name='dynamicdeviceevent',
            index=models.Index(fields=['lease'], name='dynamic_ana_lease_i_74e133_idx'),
        ),
        migrations.AddIndex(
            model_name='dynamicdevice',
            index=models.Index(fields=['status'], name='dynamic_ana_status_0ff107_idx'),
        ),
        migrations.AddIndex(
            model_name='dynamicdevice',
            index=models.Index(fields=['abi'], name='dynamic_ana_abi_0be00c_idx'),
        ),
        migrations.AddIndex(
            model_name='dynamicdevice',
            index=models.Index(fields=['api_level'], name='dynamic_ana_api_lev_83f4fe_idx'),
        ),
        migrations.AddIndex(
            model_name='dynamicdevice',
            index=models.Index(fields=['pool'], name='dynamic_ana_pool_id_15af9a_idx'),
        ),
        migrations.AddIndex(
            model_name='dynamicdevice',
            index=models.Index(fields=['status', 'abi', 'api_level'], name='dynamic_ana_status_cd14b4_idx'),
        ),
        migrations.AddIndex(
            model_name='dynamicdevice',
            index=models.Index(fields=['has_frida', 'has_mitm_ready'], name='dynamic_ana_has_fri_767ec2_idx'),
        ),
        migrations.AddConstraint(
            model_name='dynamicdevice',
            constraint=models.UniqueConstraint(fields=('host_identifier', 'name'), name='unique_dynamic_device_name_per_host'),
        ),
        migrations.AddIndex(
            model_name='dynamicanalysisjob',
            index=models.Index(fields=['audit', 'status'], name='dynamic_ana_audit_i_525b11_idx'),
        ),
        migrations.AddIndex(
            model_name='dynamicanalysisjob',
            index=models.Index(fields=['status', 'priority', 'queued_at'], name='dynamic_ana_status_499581_idx'),
        ),
        migrations.AddIndex(
            model_name='dynamicanalysisjob',
            index=models.Index(fields=['requested_device_pool', 'status'], name='dynamic_ana_request_7d39f4_idx'),
        ),
        migrations.AddIndex(
            model_name='dynamicemulatorsnapshot',
            index=models.Index(fields=['snapshot_type', 'validation_status', 'api_level', 'abi'], name='dynamic_ana_snapsho_434d8c_idx'),
        ),
        migrations.AddConstraint(
            model_name='dynamicemulatorsnapshot',
            constraint=models.UniqueConstraint(fields=('device', 'name'), name='unique_dynamic_snapshot_per_device'),
        ),
        migrations.AddConstraint(
            model_name='dynamicemulatorsnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('snapshot_type', 'SESSION_TEMP'), ('contains_target_apk', False), _connector='OR'), name='dynamic_snapshot_target_apk_temp_only'),
        ),
        migrations.AddIndex(
            model_name='dynamicsession',
            index=models.Index(fields=['audit', 'state'], name='dynamic_ana_audit_i_770be3_idx'),
        ),
        migrations.AddIndex(
            model_name='dynamicsession',
            index=models.Index(fields=['job', 'state'], name='dynamic_ana_job_id_baa66e_idx'),
        ),
        migrations.AddIndex(
            model_name='dynamicsession',
            index=models.Index(fields=['device', 'state'], name='dynamic_ana_device__dd4b28_idx'),
        ),
        migrations.AddIndex(
            model_name='dynamicsession',
            index=models.Index(fields=['cleanup_status'], name='dynamic_ana_cleanup_66da6b_idx'),
        ),
        migrations.AddConstraint(
            model_name='dynamicsession',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('state', 'COMPLETED'), _negated=True), ('cleanup_status', 'SUCCEEDED'), _connector='OR'), name='dynamic_completed_requires_cleanup'),
        ),
        migrations.AddIndex(
            model_name='dynamicsessionartifact',
            index=models.Index(fields=['session', 'artifact_type'], name='dynamic_ana_session_b52063_idx'),
        ),
        migrations.AddIndex(
            model_name='dynamicsessionartifact',
            index=models.Index(fields=['category'], name='dynamic_ana_categor_4277a3_idx'),
        ),
        migrations.AddIndex(
            model_name='dynamicsessionartifact',
            index=models.Index(fields=['redaction_state'], name='dynamic_ana_redacti_251e4c_idx'),
        ),
        migrations.AddConstraint(
            model_name='dynamicsessionartifact',
            constraint=models.UniqueConstraint(fields=('session', 'sequence_number'), name='unique_dynamic_session_artifact_sequence'),
        ),
        migrations.AddIndex(
            model_name='dynamicsessionevent',
            index=models.Index(fields=['session', 'sequence_number'], name='dynamic_ana_session_685428_idx'),
        ),
        migrations.AddIndex(
            model_name='dynamicsessionevent',
            index=models.Index(fields=['event_type', 'severity'], name='dynamic_ana_event_t_50eb02_idx'),
        ),
        migrations.AddConstraint(
            model_name='dynamicsessionevent',
            constraint=models.UniqueConstraint(fields=('session', 'sequence_number'), name='unique_dynamic_session_event_sequence'),
        ),
        migrations.AddIndex(
            model_name='dynamicsessionstage',
            index=models.Index(fields=['session', 'status'], name='dynamic_ana_session_7a66d7_idx'),
        ),
        migrations.AddIndex(
            model_name='dynamicsessionstage',
            index=models.Index(fields=['state', 'status'], name='dynamic_ana_state_1d1551_idx'),
        ),
    ]
