# Generated by Django 6.0.8 on 2026-08-11 12:37

import apps.dynamic_analysis.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_internal_agent_runtime(apps, schema_editor):
    AgentRuntime = apps.get_model("dynamic_analysis", "AgentRuntime")
    AgentRuntime.objects.update_or_create(
        name="Sprint B Internal Controller",
        defaults={
            "runtime_type": "INTERNAL_CONTROLLER",
            "status": "AVAILABLE",
            "description": (
                "Deterministic internal controller restricted to the Sprint B "
                "device readiness objective."
            ),
            "capabilities": {
                "objectives": ["DEVICE_READINESS_CHECK"],
                "tools": ["get_device_status", "take_screenshot"],
            },
            "isolation_level": "INTERNAL_ONLY",
            "endpoint_url": "",
            "enabled": True,
            "metadata": {"sprint": "B", "deterministic": True},
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0003_analysisjob_result_summary'),
        ('dynamic_analysis', '0001_initial'),
        ('storage', '0003_alter_objectstoragereference_object_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective', models.CharField(choices=[('DEVICE_READINESS_CHECK', 'Device readiness check')], max_length=64)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('TIMEOUT', 'Timeout')], default='QUEUED', max_length=32)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('result_summary', models.JSONField(blank=True, default=dict)),
                ('failure_category', models.CharField(blank=True, choices=[('HOST_AGENT_UNAVAILABLE', 'Host agent unavailable'), ('RUNTIME_UNAVAILABLE', 'Runtime unavailable'), ('TOOL_EXECUTION_FAILED', 'Tool execution failed'), ('TIMEOUT', 'Timeout'), ('INTERNAL_ERROR', 'Internal error')], max_length=64)),
                ('failure_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_runs', to='audits.audit')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_runs', to='dynamic_analysis.dynamicdevice')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_agent_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentRunStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.PositiveIntegerField()),
                ('tool_name', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped'), ('TIMEOUT', 'Timeout')], default='PENDING', max_length=32)),
                ('input_summary', models.JSONField(blank=True, default=dict)),
                ('output_summary', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('failure_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='dynamic_analysis.agentrun')),
            ],
            options={
                'ordering': ['run', 'sequence_number'],
            },
        ),
        migrations.CreateModel(
            name='AgentRunArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_type', models.CharField(choices=[('SCREENSHOT', 'Screenshot'), ('TOOL_OUTPUT', 'Tool output'), ('LOG', 'Log'), ('JSON_RESULT', 'JSON result'), ('OTHER', 'Other')], max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=128)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('object_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_run_artifacts', to='storage.objectstoragereference')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='dynamic_analysis.agentrun')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts', to='dynamic_analysis.agentrunstep')),
            ],
            options={
                'ordering': ['run', 'created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AgentRuntime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('runtime_type', models.CharField(choices=[('INTERNAL_CONTROLLER', 'Internal controller'), ('CONTAINER_SANDBOX', 'Container sandbox')], default='INTERNAL_CONTROLLER', max_length=32)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('UNAVAILABLE', 'Unavailable'), ('DEGRADED', 'Degraded'), ('DISABLED', 'Disabled')], default='AVAILABLE', max_length=32)),
                ('description', models.TextField(blank=True)),
                ('capabilities', models.JSONField(blank=True, default=apps.dynamic_analysis.models.default_agent_runtime_capabilities)),
                ('isolation_level', models.CharField(choices=[('INTERNAL_ONLY', 'Internal only'), ('CONTAINER_PLANNED', 'Container planned'), ('CONTAINER_ISOLATED', 'Container isolated')], default='INTERNAL_ONLY', max_length=32)),
                ('endpoint_url', models.URLField(blank=True)),
                ('enabled', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['enabled', 'status', 'runtime_type'], name='dynamic_ana_enabled_aea2d0_idx')],
            },
        ),
        migrations.AddField(
            model_name='agentrun',
            name='runtime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='dynamic_analysis.agentruntime'),
        ),
        migrations.RunPython(
            seed_internal_agent_runtime,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddIndex(
            model_name='agentrunstep',
            index=models.Index(fields=['run', 'status'], name='dynamic_ana_run_id_e67e11_idx'),
        ),
        migrations.AddConstraint(
            model_name='agentrunstep',
            constraint=models.UniqueConstraint(fields=('run', 'sequence_number'), name='unique_agent_run_step_sequence'),
        ),
        migrations.AddConstraint(
            model_name='agentrunstep',
            constraint=models.CheckConstraint(condition=models.Q(('sequence_number__gte', 1)), name='agent_run_step_sequence_gte_1'),
        ),
        migrations.AddIndex(
            model_name='agentrunartifact',
            index=models.Index(fields=['run', 'artifact_type'], name='dynamic_ana_run_id_b73937_idx'),
        ),
        migrations.AddIndex(
            model_name='agentrunartifact',
            index=models.Index(fields=['step', 'artifact_type'], name='dynamic_ana_step_id_fa3bfa_idx'),
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['status', 'created_at'], name='dynamic_ana_status_5f397b_idx'),
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['requested_by', 'created_at'], name='dynamic_ana_request_0ff406_idx'),
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['audit', 'created_at'], name='dynamic_ana_audit_i_86c023_idx'),
        ),
    ]
