# Generated by Django 6.0.8 on 2026-08-11 13:10

from django.db import migrations, models


def seed_container_agent_runtime(apps, schema_editor):
    AgentRuntime = apps.get_model("dynamic_analysis", "AgentRuntime")
    AgentRuntime.objects.update_or_create(
        name="Sprint C Container Sandbox",
        defaults={
            "runtime_type": "CONTAINER_SANDBOX",
            "status": "AVAILABLE",
            "description": (
                "Ephemeral deterministic container restricted to the device "
                "readiness objective and run-scoped Django tool gateway."
            ),
            "capabilities": {
                "objectives": ["DEVICE_READINESS_CHECK"],
                "tools": ["get_device_status", "take_screenshot"],
            },
            "isolation_level": "CONTAINER_ISOLATED",
            "endpoint_url": "",
            "enabled": True,
            "metadata": {"sprint": "C", "deterministic": True},
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_analysis', '0002_agentrun_agentrunstep_agentrunartifact_agentruntime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentrun',
            name='run_token_expires_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='run_token_hash',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.RunPython(
            seed_container_agent_runtime,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
