# Generated by Django 6.0.8 on 2026-08-13 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_analysis', '0004_agent_mobile_tool_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentrun',
            name='objective',
            field=models.CharField(choices=[('DEVICE_READINESS_CHECK', 'Device readiness check'), ('BASIC_APP_INTERACTION_CHECK', 'Basic app interaction check'), ('FRIDA_RUNTIME_ACTION', 'Frida runtime action'), ('FRIDA_RUNTIME_UI_MODIFICATION_PROOF', 'Frida runtime UI modification proof'), ('FRIDA_CUSTOM_SCRIPT', 'Frida custom script')], max_length=64),
        ),
    ]
