# Generated by Django 6.0.8 on 2026-08-13 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0003_analysisjob_result_summary'),
        ('dynamic_analysis', '0006_agent_runtime_frida_capabilities'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_package', models.CharField(max_length=255)),
                ('planner_provider', models.CharField(choices=[('DETERMINISTIC', 'Deterministic'), ('OPENAI', 'OpenAI')], max_length=32)),
                ('planner_model', models.CharField(max_length=128)),
                ('objective', models.CharField(max_length=500)),
                ('scope', models.TextField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('GENERATED', 'Generated'), ('VALIDATED', 'Validated'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXECUTING', 'Executing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=32)),
                ('validation_status', models.CharField(choices=[('PENDING', 'Pending'), ('PASSED', 'Passed'), ('FAILED', 'Failed')], default='PENDING', max_length=32)),
                ('generated_plan', models.JSONField(blank=True, default=dict)),
                ('normalized_plan', models.JSONField(blank=True, default=dict)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('planner_input_hash', models.CharField(blank=True, max_length=64)),
                ('plan_hash', models.CharField(blank=True, max_length=64)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_assessment_plans', to=settings.AUTH_USER_MODEL)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_plans', to='audits.audit')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assessment_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentPlanStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('step_identifier', models.CharField(max_length=64)),
                ('objective', models.CharField(max_length=500)),
                ('rationale', models.TextField()),
                ('required_tools', models.JSONField(default=list)),
                ('tool_arguments', models.JSONField(blank=True, default=dict)),
                ('expected_observation', models.TextField()),
                ('success_condition', models.TextField()),
                ('evidence_requirements', models.JSONField(default=list)),
                ('dependencies', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('PROPOSED', 'Proposed'), ('VALIDATED', 'Validated'), ('APPROVED', 'Approved'), ('EXECUTING', 'Executing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped'), ('CANCELLED', 'Cancelled')], default='PROPOSED', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='dynamic_analysis.assessmentplan')),
            ],
            options={
                'ordering': ['plan', 'sequence'],
            },
        ),
        migrations.AddIndex(
            model_name='assessmentplan',
            index=models.Index(fields=['audit', 'status'], name='dynamic_ana_audit_i_4c044f_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentplan',
            index=models.Index(fields=['target_package', 'status'], name='dynamic_ana_target__4443f2_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentplan',
            index=models.Index(fields=['validation_status', 'created_at'], name='dynamic_ana_validat_3647e0_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentplanstep',
            index=models.Index(fields=['plan', 'status'], name='dynamic_ana_plan_id_6ec7dc_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentplanstep',
            index=models.Index(fields=['plan', 'sequence'], name='dynamic_ana_plan_id_bcac28_idx'),
        ),
        migrations.AddConstraint(
            model_name='assessmentplanstep',
            constraint=models.UniqueConstraint(fields=('plan', 'sequence'), name='unique_assessment_plan_step_sequence'),
        ),
        migrations.AddConstraint(
            model_name='assessmentplanstep',
            constraint=models.UniqueConstraint(fields=('plan', 'step_identifier'), name='unique_assessment_plan_step_identifier'),
        ),
        migrations.AddConstraint(
            model_name='assessmentplanstep',
            constraint=models.CheckConstraint(condition=models.Q(('sequence__gte', 1)), name='assessment_plan_step_sequence_gte_1'),
        ),
    ]
