# Generated by Django 6.0.8 on 2026-08-13 11:56

from django.db import migrations, models


def backfill_d1_policy_status(apps, schema_editor):
    AssessmentPlan = apps.get_model("dynamic_analysis", "AssessmentPlan")
    AssessmentPlan.objects.filter(
        validation_status="PASSED",
        status__in=["GENERATED", "VALIDATED", "APPROVED"],
    ).update(policy_status="PASSED")


def reset_policy_status(apps, schema_editor):
    AssessmentPlan = apps.get_model("dynamic_analysis", "AssessmentPlan")
    AssessmentPlan.objects.update(policy_status="PENDING")


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_analysis', '0007_assessmentplan_assessmentplanstep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentplan',
            name='policy_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PASSED', 'Passed'), ('FAILED', 'Failed')], default='PENDING', max_length=32),
        ),
        migrations.AddField(
            model_name='assessmentplan',
            name='provider_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RunPython(
            backfill_d1_policy_status,
            reset_policy_status,
        ),
    ]
