# Generated by Django 6.0.8 on 2026-08-13 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_analysis', '0008_assessmentplan_policy_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agentrun',
            name='approved_plan_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='assessment_plan',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_run', to='dynamic_analysis.assessmentplan'),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='cancellation_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_agent_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='execution_contract',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='target_package',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='tool_call_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agentrunartifact',
            name='sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='agentrunartifact',
            name='size_bytes',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentrunstep',
            name='dependencies',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='agentrunstep',
            name='evidence_requirements',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='agentrunstep',
            name='is_control_step',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agentrunstep',
            name='max_retries',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agentrunstep',
            name='observation',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='agentrunstep',
            name='plan_step_identifier',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='agentrunstep',
            name='plan_step_sequence',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentrunstep',
            name='retry_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agentrunstep',
            name='timeout_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agentrunstep',
            name='tool_call_index',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='agentrun',
            name='objective',
            field=models.CharField(choices=[('DEVICE_READINESS_CHECK', 'Device readiness check'), ('BASIC_APP_INTERACTION_CHECK', 'Basic app interaction check'), ('FRIDA_RUNTIME_ACTION', 'Frida runtime action'), ('FRIDA_RUNTIME_UI_MODIFICATION_PROOF', 'Frida runtime UI modification proof'), ('FRIDA_CUSTOM_SCRIPT', 'Frida custom script'), ('ASSESSMENT_PLAN_EXECUTION', 'Approved assessment plan execution')], max_length=64),
        ),
        migrations.AlterField(
            model_name='agentrunstep',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped'), ('TIMEOUT', 'Timeout'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=32),
        ),
    ]
