# Generated by Django 6.0.8 on 2026-08-13 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0003_analysisjob_result_summary'),
        ('dynamic_analysis', '0009_agentrun_approved_plan_hash_agentrun_assessment_plan_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentplan',
            name='adaptive_cycle',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assessmentplan',
            name='parent_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adaptive_plans', to='dynamic_analysis.assessmentplan'),
        ),
        migrations.AddField(
            model_name='assessmentplan',
            name='plan_kind',
            field=models.CharField(choices=[('INITIAL', 'Initial assessment'), ('ADAPTIVE', 'Adaptive recommendation')], default='INITIAL', max_length=16),
        ),
        migrations.AddField(
            model_name='assessmentplan',
            name='source_run',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adaptive_recommendation', to='dynamic_analysis.agentrun'),
        ),
        migrations.AddIndex(
            model_name='assessmentplan',
            index=models.Index(fields=['audit', 'plan_kind', 'adaptive_cycle'], name='dynamic_ana_audit_i_1a69ae_idx'),
        ),
        migrations.AddConstraint(
            model_name='assessmentplan',
            constraint=models.CheckConstraint(condition=models.Q(('adaptive_cycle__lte', 2)), name='assessment_plan_adaptive_cycle_lte_2'),
        ),
        migrations.AddConstraint(
            model_name='assessmentplan',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('adaptive_cycle', 0), ('parent_plan__isnull', True), ('plan_kind', 'INITIAL'), ('source_run__isnull', True)), models.Q(('adaptive_cycle__gte', 1), ('parent_plan__isnull', False), ('plan_kind', 'ADAPTIVE'), ('source_run__isnull', False)), _connector='OR'), name='assessment_plan_adaptive_lineage_valid'),
        ),
    ]
