# Generated by Django 6.0.8 on 2026-08-13 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_analysis', '0010_assessmentplan_adaptive_cycle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentplan',
            name='parent_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adaptive_plans', to='dynamic_analysis.assessmentplan'),
        ),
        migrations.AlterField(
            model_name='assessmentplan',
            name='source_run',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adaptive_recommendation', to='dynamic_analysis.agentrun'),
        ),
    ]
