# Generated by Django 6.0.8 on 2026-08-15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dynamic_analysis", "0011_alter_assessmentplan_parent_plan_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentrun",
            name="capability_envelope",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="agentrun",
            name="capability_envelope_hash",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="agentrun",
            name="consecutive_failure_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="agentrun",
            name="coverage_state",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="agentrun",
            name="decision_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="agentrun",
            name="decision_model",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="agentrun",
            name="decision_provider",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="agentrun",
            name="execution_mode",
            field=models.CharField(
                choices=[
                    ("SEQUENTIAL_PLAN", "Sequential approved plan"),
                    ("ADAPTIVE_AGENT", "Adaptive assessment agent"),
                ],
                default="SEQUENTIAL_PLAN",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="agentrun",
            name="model_call_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="agentrun",
            name="termination_reason",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="agentrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("QUEUED", "Queued"),
                    ("RUNNING", "Running"),
                    ("PAUSED", "Paused for auditor"),
                    ("SUCCEEDED", "Succeeded"),
                    ("FAILED", "Failed"),
                    ("CANCELLED", "Cancelled"),
                    ("TIMEOUT", "Timeout"),
                ],
                default="QUEUED",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="AgentHypothesis",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("hypothesis_id", models.CharField(max_length=64)),
                ("family", models.CharField(choices=[("SENSITIVE_LOG_EXPOSURE", "Sensitive log exposure"), ("UI_SENSITIVE_DATA_EXPOSURE", "UI sensitive data exposure"), ("RUNTIME_TAMPERING_RESILIENCE", "Runtime tampering resilience"), ("APPLICATION_RUNTIME_STABILITY", "Application runtime stability"), ("EXPLORATORY", "Exploratory")], max_length=64)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("evidence_requirements", models.JSONField(blank=True, default=list)),
                ("status", models.CharField(choices=[("UNTESTED", "Untested"), ("ACTIVE", "Active"), ("SUPPORTED", "Supported"), ("REJECTED", "Rejected"), ("INCONCLUSIVE", "Inconclusive"), ("BLOCKED", "Blocked")], default="UNTESTED", max_length=32)),
                ("confidence", models.FloatField(default=0.0)),
                ("oracle_result", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("run", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="hypotheses", to="dynamic_analysis.agentrun")),
            ],
            options={
                "ordering": ["run", "id"],
                "constraints": [
                    models.UniqueConstraint(fields=("run", "hypothesis_id"), name="unique_agent_hypothesis_identifier"),
                    models.CheckConstraint(condition=models.Q(("confidence__gte", 0.0), ("confidence__lte", 1.0)), name="agent_hypothesis_confidence_range"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AgentActionDecision",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sequence", models.PositiveIntegerField()),
                ("contract_version", models.CharField(max_length=64)),
                ("decision_type", models.CharField(choices=[("TOOL_ACTION", "Tool action"), ("COMPLETE", "Complete"), ("NEEDS_AUDITOR", "Needs auditor")], max_length=32)),
                ("tool_name", models.CharField(blank=True, max_length=128)),
                ("arguments", models.JSONField(blank=True, default=dict)),
                ("rationale_summary", models.CharField(max_length=1000)),
                ("expected_observation", models.CharField(blank=True, max_length=1000)),
                ("evidence_goals", models.JSONField(blank=True, default=list)),
                ("confidence", models.FloatField(default=0.0)),
                ("provider", models.CharField(max_length=32)),
                ("model", models.CharField(max_length=128)),
                ("provider_metadata", models.JSONField(blank=True, default=dict)),
                ("decision_input_hash", models.CharField(max_length=64)),
                ("decision_output_hash", models.CharField(max_length=64)),
                ("validation_status", models.CharField(choices=[("PENDING", "Pending"), ("PASSED", "Passed"), ("FAILED", "Failed")], default="PENDING", max_length=16)),
                ("policy_status", models.CharField(choices=[("PENDING", "Pending"), ("PASSED", "Passed"), ("FAILED", "Failed")], default="PENDING", max_length=16)),
                ("execution_status", models.CharField(choices=[("NOT_EXECUTED", "Not executed"), ("RUNNING", "Running"), ("SUCCEEDED", "Succeeded"), ("FAILED", "Failed"), ("REJECTED", "Rejected")], default="NOT_EXECUTED", max_length=16)),
                ("observation_hash", models.CharField(blank=True, max_length=64)),
                ("failure_code", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                ("hypothesis", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="decisions", to="dynamic_analysis.agenthypothesis")),
                ("run", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="action_decisions", to="dynamic_analysis.agentrun")),
                ("run_step", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="action_decision", to="dynamic_analysis.agentrunstep")),
            ],
            options={
                "ordering": ["run", "sequence"],
                "constraints": [
                    models.UniqueConstraint(fields=("run", "sequence"), name="unique_agent_action_decision_sequence"),
                    models.CheckConstraint(condition=models.Q(("sequence__gte", 1)), name="agent_action_decision_sequence_gte_1"),
                    models.CheckConstraint(condition=models.Q(("confidence__gte", 0.0), ("confidence__lte", 1.0)), name="agent_action_decision_confidence_range"),
                ],
            },
        ),
    ]
