# Generated by Django 6.0.8 on 2026-08-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_analysis', '0020_findingvalidationmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenAICallBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=64, unique=True)),
                ('max_mission_generation_calls', models.PositiveIntegerField(default=1)),
                ('max_adaptive_decision_calls', models.PositiveIntegerField(default=6)),
                ('max_total_openai_calls', models.PositiveIntegerField(default=7)),
                ('mission_generation_call_count', models.PositiveIntegerField(default=0)),
                ('adaptive_decision_call_count', models.PositiveIntegerField(default=0)),
                ('current_openai_call_count', models.PositiveIntegerField(default=0)),
                ('provider_response_ids', models.JSONField(blank=True, default=list)),
                ('budget_exhausted_reason', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['scope'],
                'constraints': [models.CheckConstraint(condition=models.Q(('current_openai_call_count__gte', 0)), name='openai_budget_current_count_non_negative')],
            },
        ),
    ]
