# Generated by Django 6.0.8 on 2026-08-19 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_analysis', '0021_openaicallbudget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentrun',
            name='failure_category',
            field=models.CharField(blank=True, choices=[('HOST_AGENT_UNAVAILABLE', 'Host agent unavailable'), ('RUNTIME_UNAVAILABLE', 'Runtime unavailable'), ('AI_PROVIDER_FAILURE', 'AI provider failure'), ('AI_DECISION_REJECTED', 'AI decision rejected'), ('OPENAI_BUDGET_EXHAUSTED', 'OpenAI budget exhausted'), ('TOOL_EXECUTION_FAILED', 'Tool execution failed'), ('TIMEOUT', 'Timeout'), ('INTERNAL_ERROR', 'Internal error')], max_length=64),
        ),
    ]
