# Generated by Django 6.0.8 on 2026-08-20 00:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0003_analysisjob_result_summary'),
        ('dynamic_analysis', '0022_alter_agentrun_failure_category'),
        ('findings', '0002_finding_details_and_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='openaicallbudget',
            name='correlation_call_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='openaicallbudget',
            name='max_correlation_calls',
            field=models.PositiveIntegerField(default=6),
        ),
        migrations.AddField(
            model_name='openaicallbudget',
            name='max_poc_planning_calls',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='openaicallbudget',
            name='poc_planning_call_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='DynamicPoCPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_version', models.CharField(default='msap.dynamic-poc-plan/v1', max_length=64)),
                ('plan', models.JSONField(blank=True, default=dict)),
                ('plan_hash', models.CharField(blank=True, max_length=64)),
                ('hypothesis', models.TextField(blank=True)),
                ('objective', models.TextField(blank=True)),
                ('provider', models.CharField(blank=True, max_length=32)),
                ('model', models.CharField(blank=True, max_length=128)),
                ('provider_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment_plan', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dynamic_poc_plan', to='dynamic_analysis.assessmentplan')),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_poc_plans', to='audits.audit')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dynamic_poc_plans', to=settings.AUTH_USER_MODEL)),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_poc_plans', to='findings.finding')),
                ('mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dynamic_poc_plans', to='dynamic_analysis.findingvalidationmission')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['finding', 'created_at'], name='dynamic_ana_pocplan_find_idx'), models.Index(fields=['mission'], name='dynamic_ana_pocplan_mission')],
            },
        ),
        migrations.CreateModel(
            name='StaticDynamicCorrelationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_version', models.CharField(default='msap.static-dynamic-correlation/v2', max_length=64)),
                ('cache_key', models.CharField(db_index=True, max_length=64)),
                ('findings_fingerprint', models.CharField(max_length=64)),
                ('apk_sha256', models.CharField(blank=True, max_length=64)),
                ('capability_manifest_hash', models.CharField(blank=True, max_length=64)),
                ('capability_manifest', models.JSONField(blank=True, default=dict)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('candidates', models.JSONField(blank=True, default=list)),
                ('batches', models.JSONField(blank=True, default=list)),
                ('capability_gaps', models.JSONField(blank=True, default=list)),
                ('provider', models.CharField(blank=True, max_length=32)),
                ('model', models.CharField(blank=True, max_length=128)),
                ('provider_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='static_dynamic_correlation_runs', to='audits.audit')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_static_dynamic_correlation_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['audit', 'cache_key'], name='dynamic_ana_corr_cache_idx'), models.Index(fields=['audit', 'created_at'], name='dynamic_ana_corr_audit_idx')],
            },
        ),
    ]
