# Generated by Codex on 2026-08-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dynamic_analysis", "0024_fridascriptproposal_budget_50"),
    ]

    operations = [
        migrations.AddField(
            model_name="openaicallbudget",
            name="evidence_explanation_call_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="openaicallbudget",
            name="max_evidence_explanation_calls",
            field=models.PositiveIntegerField(default=30),
        ),
    ]
