# Generated by Codex on 2026-08-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dynamic_analysis", "0025_evidence_explanation_budget"),
    ]

    operations = [
        migrations.AlterField(
            model_name="openaicallbudget",
            name="max_adaptive_decision_calls",
            field=models.PositiveIntegerField(default=30),
        ),
    ]
