# Generated by Django 6.0.7 on 2026-07-13 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('created', 'Created'), ('apk_uploaded', 'APK uploaded'), ('queued', 'Queued'), ('analyzing', 'Analyzing'), ('completed', 'Completed'), ('failed', 'Failed'), ('export_ready', 'Export ready')], default='created', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
