# Generated by Django 6.0.7 on 2026-07-14 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('DRAFT', 'Draft'), ('apk_uploaded', 'APK uploaded'), ('queued', 'Queued'), ('analyzing', 'Analyzing'), ('completed', 'Completed'), ('failed', 'Failed'), ('ANALYSIS_QUEUED', 'Analysis queued'), ('ANALYSIS_RUNNING', 'Analysis running'), ('ANALYSIS_COMPLETED', 'Analysis completed'), ('ANALYSIS_FAILED', 'Analysis failed'), ('export_ready', 'Export ready')], default='created', max_length=32),
        ),
        migrations.CreateModel(
            name='AnalysisJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='QUEUED', max_length=32)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_jobs', to='audits.audit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
