# Generated by Django 6.0.7 on 2026-07-15 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apk_files', '0001_initial'),
        ('audits', '0003_analysisjob_result_summary'),
        ('storage', '0002_objectstoragereference_storage_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalizedArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_type', models.CharField(choices=[('APK_METADATA', 'APK metadata'), ('MANIFEST', 'Manifest'), ('PERMISSIONS', 'Permissions'), ('COMPONENTS', 'Components'), ('CERTIFICATE', 'Certificate'), ('STRINGS', 'Strings'), ('RESOURCES', 'Resources'), ('CODE_REFERENCES', 'Code references')], max_length=64)),
                ('source', models.CharField(max_length=128)),
                ('normalized_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apk_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_artifacts', to='apk_files.apkfile')),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_artifacts', to='audits.audit')),
                ('storage_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='normalized_artifacts', to='storage.objectstoragereference')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['audit', 'apk_file'], name='normalizati_audit_i_083234_idx'), models.Index(fields=['artifact_type', 'source'], name='normalizati_artifac_98252e_idx')],
            },
        ),
    ]
