# Generated by Django 6.0.7 on 2026-08-08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("normalization", "0002_artifact_types_and_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="normalizedartifact",
            name="artifact_type",
            field=models.CharField(
                choices=[
                    ("APK_METADATA", "APK metadata"),
                    ("MANIFEST", "Manifest"),
                    ("PERMISSIONS", "Permissions"),
                    ("COMPONENTS", "Components"),
                    ("NETWORK_SECURITY_CONFIG", "Network security config"),
                    ("CERTIFICATE", "Certificate"),
                    ("SIGNING", "Signing"),
                    ("DEX_METADATA", "DEX metadata"),
                    ("STRINGS", "Strings"),
                    ("RESOURCES", "Resources"),
                    ("CODE_REFERENCES", "Code references"),
                    ("SECRETS", "Secrets"),
                    ("CRYPTO_USAGE", "Cryptographic usage"),
                    ("WEBVIEW_USAGE", "WebView usage"),
                    ("NATIVE_LIBRARIES", "Native libraries"),
                    ("THIRD_PARTY_SDKS", "Third-party SDKs"),
                    ("URLS_AND_ENDPOINTS", "URLs and endpoints"),
                    ("PACKAGE_CONTENT", "Package content"),
                    ("RESILIENCE_SIGNALS", "Resilience signals"),
                    ("SOURCE_VERIFICATION", "Verified source observations"),
                ],
                max_length=64,
            ),
        ),
    ]
